query GetAdminByUsername($username: String!) {
  admin(where: { username: { _eq: $username } }) {
    id
    password
  }
}

mutation InsertAdmin($username: String!, $password: String!) {
  insert_admin_one(object: { username: $username, password: $password }) {
    id
  }
}
