mutation CreateFakeOrder(
  $client_address: String!
  $client_name: String!
  $client_phone: String!
  $created_at: timestamptz
) {
  insert_orders_one(
    object: {
      client_address: $client_address
      client_name: $client_name
      client_phone: $client_phone
      status: DELIVERED
      created_at: $created_at
    }
  ) {
    id
  }
}
